<a href="https://colab.research.google.com/github/akashkumar181/Panda/blob/main/PandaFunction6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Panda Function

In [1]:
import pandas as pd

In [11]:
data=pd.read_excel("/content/Car.xlsx")
data

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Citroen,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
2,Citroen,Aircross,231,127,211,93,125,136.0,68,38,41,103,201,96,1470,C2,SUV,-52,-72
3,Citroen,C5 Aircross,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
4,Citroen,e-C3,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Toyota,Taisor,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
83,Toyota,Vellfire,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
84,Volkswagen,Taigun,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
85,Volkswagen,Tiguan,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
86,Volkswagen,Virtus,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3

In [12]:
data.index #provide index and stop=n+1 row wise

RangeIndex(start=0, stop=87, step=1)

In [13]:
data.columns #provide all column name

Index(['Make', 'Model', 'January', 'February', 'March', 'April', 'May', 'June',
       'July', 'August', 'September', 'October ', 'November ', 'December',
       'Total', 'Segment', 'Body Type', 'MoM %', 'YoY %'],
      dtype='object')

In [15]:
data.describe()

,January,March,April,May,June,July,August,September,October,November,December,Total,MoM %,YoY %
count,87.000000,87.000000,87.000000,87.000000,86.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000
mean,4522.655172,4245.758621,3882.413793,4012.149425,3930.779070,3942.827586,4072.103448,4125.045977,4574.103448,4041.287356,3693.620690,49251.218391,-0.919540,398.862069
std,5557.293194,5225.786599,5022.921263,5017.870853,4902.351612,4894.956237,5018.810241,4946.506162,5433.186086,4916.494291,4696.681657,59772.950390,39.924993,3566.887394
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-87.000000
25%,207.500000,248.500000,186.000000,189.000000,138.250000,184.500000,258.000000,305.000000,298.000000,233.000000,194.500000,2945.000000,-23.500000,-27.500000
50%,1879.000000,1887.000000,1716.000000,1661.000000,1593.000000,1780.000000,1814.000000,1708.000000,2169.000000,1668.000000,1775.000000,22024.000000,-4.000000,0.000000
75%,6673.500000,6215.000000,6016.500000,5838.500000,5790.000000,5858.000000,6514.000000,6933.500000,6755.500000,5709.500000,5000.000000,75379.000000,16.500000,24.000000
max,19630.000000,17547.000000,19158.000000,19393.000000,18238.000000,17350.000000,19190.000000,17441.000000,18785.000000,16293.000000,17336.000000,202031.000000,147.000000,33270.000000

In [16]:
data.head() #show only starting 5 value by row wise from  starting

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Citroen,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
2,Citroen,Aircross,231,127,211,93,125,136.0,68,38,41,103,201,96,1470,C2,SUV,-52,-72
3,Citroen,C5 Aircross,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
4,Citroen,e-C3,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0

In [17]:
data.head(2)

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Citroen,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3

In [18]:
data.tail()   # from ending

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
82,Toyota,Taisor,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
83,Toyota,Vellfire,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
84,Volkswagen,Taigun,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
85,Volkswagen,Tiguan,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
86,Volkswagen,Virtus,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3

In [19]:
data[:2] #it provide data of o to 1 row wise

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Citroen,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3

In [20]:
data[6:11] #it gives data from 6 to 11 row wise

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
6,Honda,City,1123,1184,1116,824,1054,859.0,957,1018,895,1004,709,783,11526,C2,Sedan,10,-30
7,Honda,Elevate,4586,3184,3277,1731,1553,2151.0,1340,1723,1960,2149,1668,2334,27656,C2,SUV,40,-47
8,Hyundai,Aura,5516,5053,4883,4526,4433,4299.0,4757,4304,4462,4805,4248,3852,55138,C1,Sedan,-9,1
9,Hyundai,Alcazar,1827,1290,1420,1219,944,882.0,585,1105,2712,2204,2134,1342,17664,C2,MUV,-37,41
10,Hyundai,Creta,13212,15276,16458,15447,14662,16293.0,17350,16762,15902,17497,15452,12608,186919,C2,SUV,-18,36

In [21]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [22]:
data.index.array

<NumpyExtensionArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86]
Length: 87, dtype: int64

In [24]:
data.to_numpy()#converted into array

array([['Citroen', 'Basalt', 0, ..., 'SUV', 68, 0],
       ['Citroen', 'C3', 234, ..., 'Hatchback', 50, -3],
       ['Citroen', 'Aircross', 231, ..., 'SUV', -52, -72],
       ...,
       ['Volkswagen', 'Taigun', 1275, ..., 'SUV', 56, -5],
       ['Volkswagen', 'Tiguan', 113, ..., 'SUV', 147, -29],
       ['Volkswagen', 'Virtus', 1879, ..., 'Sedan', 55, 3]], dtype=object)

In [25]:
data.sort_index(axis=0,ascending=False) #it sort in descending order

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
86,Volkswagen,Virtus,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3
85,Volkswagen,Tiguan,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
84,Volkswagen,Taigun,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
83,Toyota,Vellfire,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
82,Toyota,Taisor,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Citroen,e-C3,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0
3,Citroen,C5 Aircross,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
2,Citroen,Aircross,231,127,211,93,125,136.0,68,38,41,103,201,96,1470,C2,SUV,-52,-72
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
0,Citroen,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0

In [28]:
data["Make"][0]="Alto" #we change the element of make column with row value 0 to alto
data

<ipython-input-28-b9b21770b2e6>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data["Make"][0]="Alto"
<ipython-input-28-b9b21770b2e6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Make"][0]="Alto"

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Alto,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
2,Citroen,Aircross,231,127,211,93,125,136.0,68,38,41,103,201,96,1470,C2,SUV,-52,-72
3,Citroen,C5 Aircross,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
4,Citroen,e-C3,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Toyota,Taisor,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
83,Toyota,Vellfire,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
84,Volkswagen,Taigun,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
85,Volkswagen,Tiguan,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
86,Volkswagen,Virtus,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3

In [29]:
data.loc[0,"Make"]="Maruti" #we change the element of make column with row value 0 to alto
data

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Maruti,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
2,Citroen,Aircross,231,127,211,93,125,136.0,68,38,41,103,201,96,1470,C2,SUV,-52,-72
3,Citroen,C5 Aircross,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
4,Citroen,e-C3,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Toyota,Taisor,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
83,Toyota,Vellfire,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
84,Volkswagen,Taigun,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
85,Volkswagen,Tiguan,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
86,Volkswagen,Virtus,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3

In [33]:
data.loc[[2,9],["Make","Model"]]#we get the element of make and model of row 2 and 9

      Make     Model
2  Citroen  Aircross
9  Hyundai   Alcazar

In [35]:
data.loc[:,["Make","Model"]] #we get all the data of make and model only

          Make        Model
0       Maruti       Basalt
1      Citroen           C3
2      Citroen     Aircross
3      Citroen  C5 Aircross
4      Citroen         e-C3
..         ...          ...
82      Toyota       Taisor
83      Toyota     Vellfire
84  Volkswagen       Taigun
85  Volkswagen       Tiguan
86  Volkswagen       Virtus

[87 rows x 2 columns]

In [36]:
data.iloc[0,1]#to get particular element 0 =row and 1=column number

'Basalt'

In [37]:
data.iloc[4,9]

150

In [38]:
data.drop("Model",axis=1)#it delete the data of whole model column wise

,Make,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Maruti,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
2,Citroen,231,127,211,93,125,136.0,68,38,41,103,201,96,1470,C2,SUV,-52,-72
3,Citroen,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
4,Citroen,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Toyota,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
83,Toyota,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
84,Volkswagen,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
85,Volkswagen,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
86,Volkswagen,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3

In [39]:
data.drop(2,axis=0)#it delete the data of whole row 2

,Make,Model,January,February,March,April,May,June,July,August,September,October,November,December,Total,Segment,Body Type,MoM %,YoY %
0,Maruti,Basalt,0,0,0,0,0,0.0,0,579,341,221,47,79,1267,C2,SUV,68,0
1,Citroen,C3,234,211,265,251,155,77.0,90,507,300,300,200,300,2890,C1,Hatchback,50,-3
3,Citroen,C5 Aircross,1,0,0,1,0,0.0,0,1,1,4,0,1,9,D2,SUV,0,-50
4,Citroen,e-C3,184,83,530,59,235,126.0,177,150,28,89,61,90,1812,C1,SUV,48,0
5,Honda,Amaze,2972,2774,2678,1796,2215,1794.0,2327,2585,2820,2393,2628,3708,30690,C1,Sedan,41,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Toyota,Taisor,0,0,0,0,2180,3185.0,2640,3213,2278,3092,3620,2628,22836,C1,Hatchback,-27,0
83,Toyota,Vellfire,61,57,38,5,62,142.0,113,114,87,115,86,63,943,Premium,MUV,-27,70
84,Volkswagen,Taigun,1275,1286,1588,1758,1561,1519.0,1564,1628,1611,2028,1497,2335,19650,C2,SUV,56,-5
85,Volkswagen,Tiguan,113,102,94,108,102,85.0,77,73,86,79,79,195,1193,D2,SUV,147,-29
86,Volkswagen,Virtus,1879,1631,1847,1183,1610,1656.0,1766,1876,1697,2351,1457,2257,21210,C2,Sedan,55,3